# Generated by Django 3.2.5 on 2021-10-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50, null=True)),
                ('session_key', models.CharField(max_length=50, null=True)),
                ('my_session_key', models.CharField(max_length=50, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
