# Generated by Django 3.2.5 on 2021-10-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_userfavori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavori',
            name='favorite',
        ),
        migrations.AddField(
            model_name='userfavori',
            name='entry_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userfavori',
            name='entry_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
