# Generated by Django 3.2.5 on 2021-10-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_auto_20211014_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('proof', models.TextField(null=True)),
                ('remark', models.TextField(null=True)),
                ('example', models.TextField(null=True)),
                ('source', models.CharField(max_length=200, null=True)),
                ('chinese', models.CharField(max_length=1000, null=True)),
                ('author', models.TextField(null=True)),
            ],
        ),
    ]
