# Generated by Django 3.2.5 on 2021-10-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_name',
            field=models.TextField(null=True),
        ),
    ]
