# Generated by Django 3.2.5 on 2021-10-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_userinfo_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='my_session_key',
            new_name='user_id',
        ),
    ]
