# Generated by Django 3.2.5 on 2021-10-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0006_rename_my_session_key_userinfo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_name',
            new_name='nick_name',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avatar_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='language',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='province',
            field=models.TextField(null=True),
        ),
    ]
