# Generated by Django 3.2.5 on 2021-10-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0007_auto_20211020_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(null=True),
        ),
    ]
