# Generated by Django 3.2.5 on 2021-10-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0008_alter_userinfo_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50, null=True)),
                ('token', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
