# Generated by Django 3.2.5 on 2021-10-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0009_userfavoritoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=50, null=True)),
                ('secret', models.CharField(max_length=50, null=True)),
                ('wechat_url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
